# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e104a288c72922b9038ded6ad064930db565d57c6eb129370a395e59aa271c9e5fa9c09997f423d0eb438864ae7b6d5003b4cd9da1057dd5c89831d7798d8ef

test:
  secret_key_base: 5d5a48bb9f649269f2b8e02066ea477b6cd192cf6a03ae0a6d1dadeb50db66e6af84a29d5fcf2deaf11ee44db181881f5562a1b1b9ab677e032f3fd77a4ccc40

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
